# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b29110895da0901c30c510f01882244272c88842cc81f4d8e0e96998a37e7e0af6cb2996f9ce091cc62e1797216c5246aaa0fa3ed007505f3221e8d16dde5c5

test:
  secret_key_base: 87a6c62ee9dd92c92979c38a51333c86fe00284c7d0f9a7433dd4b1807e57630cddf8f407a77f1cc237562d1abd728214ee24026b820fb2085ddb99977f6d7c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
